version: '2'

services:
  cryptopus:
    # docker build . -t dashboard:latest
    image: dashboard:latest
    container_name: dashboard
    environment:
      # get api-key: https://thedogapi.com/
      DOGGO_KEY: change-me
      # get api-key: https://developer.srgssr.ch/
      SRG_API_KEY: change-me
      SRG_API_SECRET: change-me
    ports:
      - 3030:3030
